#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

puts "By considering the terms in the Fibonacci sequence whose values do not exceed four million"
puts "find the sum of the even-valued terms"

x = 0 # count of the fibonacci sequence
totalsum = 0 # total sum of even valued terms

# recursive for Fibonacci
def fibonacci( n )
  # the first two terms in Fibonacci are fixes: 0 and 1
    return  n  if n <= 1 
    fibonacci( n - 1 ) + fibonacci( n - 2 )
end 

# for all Fibonacci values less than 4 million check which are even and add that value to the sum
while fibonacci(x) <= 4000000
  if fibonacci(x) % 2 == 0
    totalsum += fibonacci(x)
  end
  x += 1
end

print "\nThe total sum of the even-valued fibonacci terms not exceeding 4 million is: \n", totalsum
